"""
Weaviate Retrieval Plan Schema

Defines the structure for LLM-generated retrieval plans.
These plans are deterministic, safe, and auditable.
"""

from typing import List, Dict, Any, Literal
from pydantic import BaseModel, Field


class PageRangeFilter(BaseModel):
    """Filter by page number range."""
    start_page: int = Field(..., ge=1, description="Starting page number (inclusive)")
    end_page: int = Field(..., ge=1, description="Ending page number (inclusive)")


class SectionFilter(BaseModel):
    """Filter by section number."""
    section_numbers: List[str] = Field(..., description="Section numbers to retrieve (e.g., ['4.1', '4.1.1'])")


class KeywordSearch(BaseModel):
    """Keyword-based semantic search."""
    keywords: List[str] = Field(..., min_items=1, max_items=10, description="Search keywords")
    match_all: bool = Field(default=False, description="If true, all keywords must be present. If false, any keyword matches.")
    proximity: int = Field(default=100, ge=0, le=500, description="Max word distance between keywords (0 = same sentence)")


class ConceptSearch(BaseModel):
    """Semantic search for concepts/topics."""
    concept: str = Field(..., description="Concept or topic to search for")
    expand_synonyms: bool = Field(default=True, description="Include semantically similar terms")
    min_relevance: float = Field(default=0.7, ge=0.0, le=1.0, description="Minimum semantic similarity score")


class RetrievalStep(BaseModel):
    """
    A single retrieval operation in the plan.
    Each step is independent and can be executed in parallel or sequence.
    """
    step_id: str = Field(..., description="Unique identifier for this step (e.g., 'step_1')")
    step_description: str = Field(..., description="Human-readable explanation of what this step retrieves and why")

    retrieval_method: Literal["page_range", "section", "keyword", "concept", "hybrid"] = Field(
        ...,
        description="Method to use for retrieval"
    )

    # Filters (at least one required)
    page_range: PageRangeFilter | None = None
    section: SectionFilter | None = None
    keyword_search: KeywordSearch | None = None
    concept_search: ConceptSearch | None = None

    # Metadata
    expected_chunks: int = Field(default=10, ge=1, le=50, description="Expected number of chunks to retrieve")
    priority: Literal["high", "medium", "low"] = Field(default="medium", description="Retrieval priority")
    depends_on: List[str] = Field(default=[], description="Step IDs this step depends on")


class RetrievalPlan(BaseModel):
    """
    Complete retrieval plan for answering a query.
    Generated by LLM, executed by agent.
    """
    query: str = Field(..., description="Original normalized query")

    reasoning: str = Field(
        ...,
        description="Detailed explanation of why RAG is needed and what information must be retrieved"
    )

    strategy: Literal["focused", "exploratory", "comparative", "comprehensive"] = Field(
        ...,
        description="Overall retrieval strategy: focused (specific text), exploratory (find relevant sections), comparative (multiple sections), comprehensive (broad coverage)"
    )

    steps: List[RetrievalStep] = Field(
        ...,
        min_items=1,
        max_items=5,
        description="Ordered retrieval steps (executed sequentially or in parallel based on dependencies)"
    )

    expected_answer_type: Literal["requirement", "procedure", "definition", "comparison", "citation", "analysis"] = Field(
        ...,
        description="Type of answer expected after retrieval"
    )

    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence that this plan will yield sufficient information")

    fallback_to_norag: bool = Field(
        default=False,
        description="If retrieval yields no results, can question be answered with indices alone?"
    )

    estimated_tokens: int = Field(..., ge=0, description="Estimated total tokens for retrieved chunks")


# Example retrieval plans for different query types

EXAMPLE_PLANS = {
    "specific_requirement": {
        "query": "What are the specific safety requirements for software verification in section 4.2?",
        "reasoning": "Query requires exact requirement text from section 4.2. Index metadata shows section exists but summaries don't contain specific requirement details.",
        "strategy": "focused",
        "steps": [
            {
                "step_id": "step_1",
                "step_description": "Retrieve all chunks from section 4.2 that contain requirement keywords",
                "retrieval_method": "hybrid",
                "section": {"section_numbers": ["4.2", "4.2.1", "4.2.2", "4.2.3"]},
                "keyword_search": {
                    "keywords": ["requirement", "shall", "must", "safety", "verification"],
                    "match_all": False,
                    "proximity": 50
                },
                "expected_chunks": 15,
                "priority": "high",
                "depends_on": []
            }
        ],
        "expected_answer_type": "requirement",
        "confidence": 0.95,
        "fallback_to_norag": False,
        "estimated_tokens": 6000
    },

    "procedural_steps": {
        "query": "What is the process for conducting hazard analysis according to this document?",
        "reasoning": "Query requires detailed procedural steps. Topic Index identifies hazard analysis is in sections 3.4 and 5.2, but detailed steps require full text retrieval.",
        "strategy": "focused",
        "steps": [
            {
                "step_id": "step_1",
                "step_description": "Retrieve procedural content about hazard analysis from section 3.4",
                "retrieval_method": "hybrid",
                "section": {"section_numbers": ["3.4", "3.4.1", "3.4.2"]},
                "concept_search": {
                    "concept": "hazard analysis process steps methodology",
                    "expand_synonyms": True,
                    "min_relevance": 0.75
                },
                "expected_chunks": 10,
                "priority": "high",
                "depends_on": []
            },
            {
                "step_id": "step_2",
                "step_description": "Retrieve additional procedural guidance from section 5.2",
                "retrieval_method": "hybrid",
                "section": {"section_numbers": ["5.2"]},
                "keyword_search": {
                    "keywords": ["hazard", "analysis", "step", "procedure", "method"],
                    "match_all": False,
                    "proximity": 100
                },
                "expected_chunks": 8,
                "priority": "medium",
                "depends_on": []
            }
        ],
        "expected_answer_type": "procedure",
        "confidence": 0.90,
        "fallback_to_norag": False,
        "estimated_tokens": 7200
    },

    "citation_context": {
        "query": "Show me the exact text where Defence Standard 00-055 is referenced and what it says about safety-related software",
        "reasoning": "Query requires exact citation text. Reference Index shows DS 00-055 is cited on pages 5, 12, and 18, but need actual quoted text and context.",
        "strategy": "focused",
        "steps": [
            {
                "step_id": "step_1",
                "step_description": "Retrieve chunks from pages where DS 00-055 is cited",
                "retrieval_method": "hybrid",
                "page_range": {"start_page": 5, "end_page": 5},
                "keyword_search": {
                    "keywords": ["Defence Standard", "00-055", "DS 00-055", "DefStan 00-055"],
                    "match_all": False,
                    "proximity": 20
                },
                "expected_chunks": 5,
                "priority": "high",
                "depends_on": []
            },
            {
                "step_id": "step_2",
                "step_description": "Retrieve chunks from page 12",
                "retrieval_method": "hybrid",
                "page_range": {"start_page": 12, "end_page": 12},
                "keyword_search": {
                    "keywords": ["Defence Standard", "00-055", "safety-related software"],
                    "match_all": False,
                    "proximity": 50
                },
                "expected_chunks": 5,
                "priority": "high",
                "depends_on": []
            },
            {
                "step_id": "step_3",
                "step_description": "Retrieve chunks from page 18",
                "retrieval_method": "hybrid",
                "page_range": {"start_page": 18, "end_page": 18},
                "keyword_search": {
                    "keywords": ["Defence Standard", "00-055"],
                    "match_all": False,
                    "proximity": 20
                },
                "expected_chunks": 5,
                "priority": "medium",
                "depends_on": []
            }
        ],
        "expected_answer_type": "citation",
        "confidence": 0.95,
        "fallback_to_norag": False,
        "estimated_tokens": 6000
    },

    "comparative_analysis": {
        "query": "Compare the verification requirements in section 4.2 with the validation requirements in section 4.3",
        "reasoning": "Query requires comparing content across two sections. Need full text from both to identify similarities and differences.",
        "strategy": "comparative",
        "steps": [
            {
                "step_id": "step_1",
                "step_description": "Retrieve verification requirements from section 4.2",
                "retrieval_method": "hybrid",
                "section": {"section_numbers": ["4.2", "4.2.1", "4.2.2"]},
                "keyword_search": {
                    "keywords": ["verification", "requirement", "shall", "must"],
                    "match_all": False,
                    "proximity": 50
                },
                "expected_chunks": 12,
                "priority": "high",
                "depends_on": []
            },
            {
                "step_id": "step_2",
                "step_description": "Retrieve validation requirements from section 4.3",
                "retrieval_method": "hybrid",
                "section": {"section_numbers": ["4.3", "4.3.1", "4.3.2"]},
                "keyword_search": {
                    "keywords": ["validation", "requirement", "shall", "must"],
                    "match_all": False,
                    "proximity": 50
                },
                "expected_chunks": 12,
                "priority": "high",
                "depends_on": []
            }
        ],
        "expected_answer_type": "comparison",
        "confidence": 0.90,
        "fallback_to_norag": False,
        "estimated_tokens": 9600
    }
}
