name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync
        run: |
          curl -X POST "https://voila-api.mmopro.in/sync-app" \
            -H "Content-Type: application/json" \
            -d '{"app": "test_nextjs_test-1769510650464", "repo": "https://github.com/BharatSharma34/test_nextjs_test-1769510650464.git", "github_token": "${{ secrets.PRIVATE_GITHUB_TOKEN }}"}'